import { useState } from "react";
import { BarChart3, CalendarDays, Car, CircleParking, Plus, Store, Tag, Users } from "lucide-react";

import { DashboardCard, MetricStrip } from "@/components/mallq/Cards";
import { MallQModal, SearchBar } from "@/components/mallq/Controls";
import { AdminShell, ContentCard } from "@/components/mallq/Navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { adminStats, categoryDistribution, events, footfallData, offers, parkingStats, recentActivities, stores, users } from "@/lib/mallq-data";

export function AdminDashboardPage() {
  return <AdminShell title="Dashboard" description="Mall operations at a glance, using frontend mock data."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-5">{adminStats.map((stat, index) => <DashboardCard key={stat.label} {...stat} icon={[<Users key="users" />, <Store key="stores" />, <Tag key="offers" />, <CalendarDays key="events" />, <Car key="parking" />][index]} />)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_0.8fr]"><ContentCard><PanelTitle title="Historical Footfall" subtitle="Mock historical visits by weekday" /><BarChart /></ContentCard><ContentCard><PanelTitle title="Store category distribution" subtitle="Current mock directory mix" /><Distribution /></ContentCard></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-3"><ContentCard><PanelTitle title="Recent activity" subtitle="Latest management updates" /><div className="mt-5 grid gap-4">{recentActivities.map((item) => <div key={item} className="border-l-2 border-primary pl-4 text-sm text-muted-foreground">{item}</div>)}</div></ContentCard><ContentCard><PanelTitle title="Recent offers" subtitle="Currently visible to customers" /><div className="mt-4 grid gap-3">{offers.slice(0, 3).map((offer) => <CompactRow key={offer.id} title={offer.title} meta={offer.storeName} />)}</div></ContentCard><ContentCard><PanelTitle title="Upcoming events" subtitle="Next on the mall calendar" /><div className="mt-4 grid gap-3">{events.map((event) => <CompactRow key={event.id} title={event.title} meta={event.date} />)}</div></ContentCard></div>
  </AdminShell>;
}

export function ManageStoresPage() {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false);
  const rows = stores.filter((store) => `${store.name} ${store.category}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminShell title="Manage Stores" description="Review and maintain store directory records."><Toolbar query={query} setQuery={setQuery} placeholder="Search stores" actionLabel="Add Store" onAction={() => setOpen(true)} /><DataTable headers={["Store", "Category", "Floor", "Status", "Actions"]}>{rows.map((store) => <TableRow key={store.id}><TableCell className="font-semibold">{store.name}</TableCell><TableCell>{store.category}</TableCell><TableCell>{store.floor}</TableCell><TableCell><StatusBadge status={store.status} /></TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="outline">Edit</Button><Button size="sm" variant="ghost">Delete</Button></div></TableCell></TableRow>)}</DataTable><AddModal open={open} setOpen={setOpen} title="Add Store" /></AdminShell>;
}

export function ManageUsersPage() {
  const [query, setQuery] = useState(""); const rows = users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminShell title="Manage Users" description="Browse mock customer profiles and account status."><Toolbar query={query} setQuery={setQuery} placeholder="Search users" /><DataTable headers={["User", "Email", "Status", "Registration date", "Actions"]}>{rows.map((user) => <TableRow key={user.email}><TableCell className="font-semibold">{user.name}</TableCell><TableCell>{user.email}</TableCell><TableCell><StatusBadge status={user.status} /></TableCell><TableCell>{user.registered}</TableCell><TableCell><Button size="sm" variant="outline">View details</Button></TableCell></TableRow>)}</DataTable></AdminShell>;
}

export function ManageOffersPage() {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const rows = offers.filter((offer) => `${offer.title} ${offer.storeName}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminShell title="Manage Offers" description="Create, edit, and control offer visibility."><Toolbar query={query} setQuery={setQuery} placeholder="Search offers" actionLabel="Add Offer" onAction={() => setOpen(true)} /><DataTable headers={["Offer", "Store", "Discount", "Validity", "Active", "Actions"]}>{rows.map((offer) => <TableRow key={offer.id}><TableCell className="font-semibold">{offer.title}</TableCell><TableCell>{offer.storeName}</TableCell><TableCell><Badge variant="soft">{offer.discount}</Badge></TableCell><TableCell>{offer.validUntil}</TableCell><TableCell><Switch defaultChecked={offer.status === "Active"} aria-label={`Toggle ${offer.title}`} /></TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="outline">Edit</Button><Button size="sm" variant="ghost">Delete</Button></div></TableCell></TableRow>)}</DataTable><AddModal open={open} setOpen={setOpen} title="Add Offer" /></AdminShell>;
}

export function ManageEventsPage() {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const rows = events.filter((event) => event.title.toLowerCase().includes(query.toLowerCase()));
  return <AdminShell title="Manage Events" description="Maintain the MallQ events calendar."><Toolbar query={query} setQuery={setQuery} placeholder="Search events" actionLabel="Add Event" onAction={() => setOpen(true)} /><DataTable headers={["Event", "Date", "Location", "Status", "Actions"]}>{rows.map((event) => <TableRow key={event.id}><TableCell className="font-semibold">{event.title}</TableCell><TableCell>{event.date}</TableCell><TableCell>{event.location}</TableCell><TableCell><StatusBadge status={event.status} /></TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="outline">Edit</Button><Button size="sm" variant="ghost">Delete</Button></div></TableCell></TableRow>)}</DataTable><AddModal open={open} setOpen={setOpen} title="Add Event" /></AdminShell>;
}

export function ManageParkingPage() {
  const occupancy = Math.round(parkingStats.occupied / parkingStats.total * 100);
  return <AdminShell title="Manage Parking" description="Frontend-only parking overview prepared for a future API feed."><MetricStrip items={[{ label: "Total capacity", value: parkingStats.total.toLocaleString(), tone: "lavender" }, { label: "Occupied", value: parkingStats.occupied.toLocaleString(), tone: "blush" }, { label: "Available", value: parkingStats.available.toLocaleString(), tone: "sage" }, { label: "Occupancy", value: `${occupancy}%`, tone: "sky" }]} /><div className="mt-6 grid gap-6 lg:grid-cols-2"><ContentCard><PanelTitle title="Vehicle type breakdown" subtitle="Configured mock capacity" /><div className="mt-6 grid gap-4 sm:grid-cols-2"><Vehicle icon={<Car />} label="Four-wheelers" value={parkingStats.fourWheeler} /><Vehicle icon={<CircleParking />} label="Two-wheelers" value={parkingStats.twoWheeler} /></div></ContentCard><ContentCard><PanelTitle title="Integration status" subtitle="No live parking feed is connected" /><div className="mt-6 rounded-2xl border border-dashed border-border bg-sage-soft p-6"><p className="font-display text-xl font-bold">API-ready layout</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Capacity fields, occupancy indicators, and vehicle breakdowns can be mapped to a real parking service in a later phase.</p></div></ContentCard></div></AdminShell>;
}

export function AnalyticsPage() {
  return <AdminShell title="Analytics" description="Professional reporting with clearly labelled mock and historical data."><div className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]"><ContentCard><PanelTitle title="Historical Footfall" subtitle="Mock historical visits—no prediction data" /><BarChart /></ContentCard><ContentCard className="border-dashed border-primary bg-blush-soft"><Badge variant="outline">Future module</Badge><h2 className="mt-5 font-display text-2xl font-extrabold">AI Footfall Prediction</h2><p className="mt-3 leading-7 text-muted-foreground">Machine learning prediction module will be connected here.</p></ContentCard></div><div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-4"><AnalyticsMetric title="Store performance" value="168 stores" note="Mock directory coverage" /><AnalyticsMetric title="Customer activity" value="12.4k users" note="Mock registered users" /><AnalyticsMetric title="Offer engagement" value="42 offers" note="Mock active offer set" /><AnalyticsMetric title="Parking usage" value="64%" note="Mock occupancy snapshot" /></div><div className="mt-6"><ContentCard><PanelTitle title="Store category distribution" subtitle="Mock current directory mix" /><Distribution /></ContentCard></div></AdminShell>;
}

export function SettingsPage() {
  return <AdminShell title="Settings" description="Frontend preference controls for the MallQ admin experience."><div className="grid max-w-3xl gap-6"><ContentCard><PanelTitle title="Notification preferences" subtitle="Choose which mock admin alerts are enabled" /><div className="mt-6 grid gap-5"><Setting label="Store update alerts" checked /><Setting label="Offer expiry reminders" checked /><Setting label="Event schedule changes" checked /><Setting label="Parking occupancy warnings" /></div></ContentCard><ContentCard><PanelTitle title="Phase 1 status" subtitle="Frontend-only implementation" /><p className="mt-4 text-sm leading-7 text-muted-foreground">Authentication, persistence, external APIs, machine learning, and deployment are intentionally not connected in this phase.</p></ContentCard></div></AdminShell>;
}

function PanelTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div><h2 className="font-display text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div>; }
function CompactRow({ title, meta }: { title: string; meta: string }) { return <div className="rounded-xl bg-surface-warm p-3"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{meta}</p></div>; }
function BarChart() { return <div className="mt-8 flex h-56 items-end gap-2 sm:gap-4">{footfallData.map((item) => <div key={item.label} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="hidden text-xs font-semibold text-muted-foreground sm:block">{item.value}</span><div className={`w-full max-w-12 rounded-t-lg ${item.height} ${item.tone}`} /><span className="text-xs font-semibold text-muted-foreground">{item.label}</span></div>)}</div>; }
function Distribution() { return <div className="mt-6 grid gap-4">{categoryDistribution.map((item) => <div key={item.label}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{item.label}</span><span className="text-muted-foreground">{item.value}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${item.width} ${item.tone}`} /></div></div>)}</div>; }
function Toolbar({ query, setQuery, placeholder, actionLabel, onAction }: { query: string; setQuery: (value: string) => void; placeholder: string; actionLabel?: string; onAction?: () => void }) { return <div className="mb-6 flex flex-col gap-3 rounded-2xl border border-border bg-card p-4 shadow-soft sm:flex-row sm:items-center sm:justify-between"><SearchBar value={query} onChange={setQuery} placeholder={placeholder} className="w-full sm:max-w-md" />{actionLabel && <Button onClick={onAction}><Plus />{actionLabel}</Button>}</div>; }
function DataTable({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-soft"><Table><TableHeader><TableRow className="bg-surface-warm">{headers.map((header) => <TableHead key={header} className="px-4">{header}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table></div>; }
function StatusBadge({ status }: { status: string }) { return <Badge variant={status === "Active" || status === "Open" || status === "Upcoming" ? "sage" : status === "Inactive" || status === "Closed" ? "soft" : "lavender"}>{status}</Badge>; }
function AddModal({ open, setOpen, title }: { open: boolean; setOpen: (open: boolean) => void; title: string }) { return <MallQModal open={open} onOpenChange={setOpen} title={title} description="This form is a frontend-only preview. Data is not persisted yet."><div className="grid gap-4"><Input placeholder="Name or title" /><Input placeholder="Category" /><Input placeholder="Location or validity" /><Button onClick={() => setOpen(false)}>Save mock record</Button></div></MallQModal>; }
function Vehicle({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-2xl bg-surface-warm p-5"><div className="text-primary [&_svg]:size-6">{icon}</div><p className="mt-5 text-sm font-semibold text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl font-extrabold">{value}</p></div>; }
function AnalyticsMetric({ title, value, note }: { title: string; value: string; note: string }) { return <ContentCard><BarChart3 className="size-6 text-primary" /><h2 className="mt-5 font-display text-lg font-bold">{title}</h2><p className="mt-3 text-2xl font-extrabold">{value}</p><p className="mt-2 text-sm text-muted-foreground">{note}</p></ContentCard>; }
function Setting({ label, checked = false }: { label: string; checked?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className="font-semibold">{label}</span><Switch defaultChecked={checked} aria-label={label} /></div>; }
